name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/other-configs/labels.yml

permissions:
  contents: read

jobs:
  configure-labels:
    name: Configure labels
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          manifest: .github/other-configs/labels.yml
